### ISSUE TITLE
Creation Complete view convenience handler

### ISSUE THREAD

**Issue by redannick** [mesmotronic/conbo#1]
Hi, would it be possible to have a convenience method added to view which is triggered on CREATION_COMPLETE please? I often want to run code at this point and it feels like adding a listener for this is boilerplate that could be within the View class rather than in each of my custom Views. 

Happy to submit a PR if it's a suitable idea

**Comment by neilrackett** [comment]
The current thinking was actually to move in the other direction, using more events and fewer methods, but I can see the logic in a `View.creationComplete()` convenience method, as the event is so commonly used.

It should be easy to add, with a stub method in `View` and a call just after the `CREATION_COMPLETE` event on line 611, perhaps?

Happy to consider a PR (use `dev` branch); be sure to include JSDoc and updates to TS definitions.
